kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: influx-bridge
  labels:
    app: influx-bridge
spec:
  triggers: 
    - type: ImageChange
  source: 
    git:
      uri: "https://github.com/ctron/kafka-influxdb-bridge"
      ref: master
  strategy: 
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: fuse7-java-openshift:1.2
  output: 
    to:
      kind: ImageStreamTag
      name: influx-bridge:latest
