kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: influx-bridge
  labels:
    app: influx-bridge
    deploymentconfig: influx-bridge
spec:
  template: 
    metadata:
      labels:
        app: influx-bridge
        deploymentconfig: influx-bridge
    spec:
      containers:
        - name: bridge
          image: influx-bridge
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_PROJECT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: telemetry-bridge
                  key: kafka.cluster.name
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: influx-bridge
                  key: kafka.groupId
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: telemetry-bridge
                  key: kafka.topic
            - name: SPRING_INFLUX_USER
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: app.username
            - name: SPRING_INFLUX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: app.password
            - name: BRIDGE_INFLUXDB_HOST
              valueFrom:
                configMapKeyRef:
                  name: influx-bridge
                  key: influxdb.host
            - name: BRIDGE_INFLUXDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: influxdb-config
                  key: databaseName
          resources:
            limits:
              memory: 256Mi
          ports:
            - containerPort: 8778
              protocol: TCP
              name: jolokia
          volumeMounts:
      volumes:

  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - bridge
        from:
          kind: ImageStreamTag
          name: influx-bridge:latest

  strategy: 
    type: Rolling
  replicas: 1
  selector:
    app: influx-bridge
    deploymentconfig: influx-bridge
