kind: Service
apiVersion: v1
metadata:
 labels:
   app: influxdb
   deploymentconfig: influxdb
 name: influxdb
spec:
 ports:
 - name: api
   port: 8086
   protocol: TCP
   targetPort: 8086
 selector:
   app: influxdb
   deploymentconfig: influxdb
