kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: telemetry-bridge-quarkus
  labels:
    app: telemetry-bridge
    deploymentconfig: telemetry-bridge-quarkus
  annotations:
    app.openshift.io/connects-to: iot-cluster-kafka
spec:
  template: 
    metadata:
      labels:
        app: telemetry-bridge
        deploymentconfig: telemetry-bridge-quarkus
    spec:
      containers:
        - name: bridge
          image: telemetry-bridge-quarkus-app
          imagePullPolicy: IfNotPresent
          env:
            - name: IOT_TENANT
              valueFrom:
                configMapKeyRef:
                  name: telemetry-bridge
                  key: iot.tenant
            - name: AMQP_HOST
              valueFrom:
                configMapKeyRef:
                  name: telemetry-bridge
                  key: amqp.host
            - name: AMQP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telemetry-bridge
                  key: amqp.username
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telemetry-bridge
                  key: amqp.password
            - name: KAFKA_PROJECT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: telemetry-bridge
                  key: kafka.cluster.name
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: telemetry-bridge
                  key: kafka.topic
          resources:
            limits:
              memory: 256Mi

  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - bridge
        from:
          kind: ImageStreamTag
          name: telemetry-bridge-quarkus-app:latest

  strategy: 
    type: Rolling
  replicas: 1
  selector:
    app: telemetry-bridge
    deploymentconfig: telemetry-bridge-quarkus
