kind: Kafka
apiVersion: kafka.strimzi.io/v1beta1
metadata:
  name: iot-cluster
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: '2.2'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      plain: {}
      tls: {}
      external:
        type: route
        authentication:
          type: tls
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
    version: 2.2.1
    template:
      pod:
        securityContext: {}
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    template:
      pod:
        securityContext: {}
